version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"  # Mapeie a porta 3000 do host para a porta 3000 do contêiner
    volumes:
      - .:/app
    environment:
      NODE_ENV: development